apiVersion: v1
kind: Service
metadata:
  name: frontend-nginx-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    # 가비아에서 도메인 생성하고 Router53으로 생성한 도메인을 등록한다. (네임서버 변경 필요)
    # A 레코드 생성 후 http 접속 확인
    # AWS Certificate Manager에서 인증서의 ARN 정보를 복사해서 붙여 넣는다. 
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-northeast-2:579573111875:certificate/e9f928bd-f44f-40ea-851f-2f9f38b071cc
spec:
  selector:
    app: frontend-nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 80
  type: LoadBalancer






